version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '09:00'
      timezone: Asia/Seoul
    open-pull-requests-limit: 5
    commit-message:
      prefix: build(deps)
      include: scope
    labels:
      - dependencies
      - go

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '09:00'
      timezone: Asia/Seoul
    open-pull-requests-limit: 5
    commit-message:
      prefix: ci(deps)
      include: scope
    labels:
      - dependencies
      - github-actions
